/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vektra.View;

/**
 *
 * @author santi
 */
public class AnadirVehiculo extends javax.swing.JPanel {

    /**
     * Creates new form AnadirVehiculo
     */
    public AnadirVehiculo() {
        initComponents();
        vektra.Util.FontUtil.applyCustomFont(this);
    }

    private static final java.awt.Color COLOR_CAMPO = new java.awt.Color(51, 51, 51);
    private static final java.awt.Color COLOR_ERROR = new java.awt.Color(200, 50, 50);
    private static final java.awt.Color COLOR_OK    = new java.awt.Color(39, 174, 96);
    private static final java.awt.Color COLOR_TEXTO = new java.awt.Color(204, 204, 204);

    // Inicialización adicional
    {
        // Se ejecuta después del initComponents cuando el constructor termina
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                initColors();
                initPlaceholders();
                initValidaciones();
                btnAnadirVehiculo.addActionListener(new java.awt.event.ActionListener() {
                    @Override
                    public void actionPerformed(java.awt.event.ActionEvent e) {
                        btnAnadirVehiculoActionPerformed(e);
                    }
                });
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        IDvehiculotxt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        aniofabricacionVehiculotxt = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        cmbLineas = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cmbCapacidad = new javax.swing.JComboBox<>();
        cmbConductoresDisponibles = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        btnAnadirVehiculo = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Añadir Vehiculo");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("Registra un nuevo vehículo en la flota del sistema");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 153, 153));
        jLabel3.setText("Identificación:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 153, 153));
        jLabel4.setText("Placa/Matricula:");

        IDvehiculotxt.setBackground(new java.awt.Color(0, 0, 0));
        IDvehiculotxt.setForeground(new java.awt.Color(204, 204, 204));
        IDvehiculotxt.setText("Ej. VTRAIN-928");
        IDvehiculotxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDvehiculotxtActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 153, 153));
        jLabel5.setText("Línea Asignada:");

        aniofabricacionVehiculotxt.setBackground(new java.awt.Color(0, 0, 0));
        aniofabricacionVehiculotxt.setForeground(new java.awt.Color(204, 204, 204));
        aniofabricacionVehiculotxt.setText("Ej. 2023");
        aniofabricacionVehiculotxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aniofabricacionVehiculotxtActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(153, 153, 153));
        jLabel6.setText("Asignación:");

        cmbLineas.setBackground(new java.awt.Color(51, 51, 51));
        cmbLineas.setForeground(new java.awt.Color(255, 255, 255));
        cmbLineas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Línea Roja", "Línea Azul", "Línea Amarilla", "Línea Verde", " " }));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(153, 153, 153));
        jLabel7.setText("Año de Fabricación:");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(153, 153, 153));
        jLabel8.setText("Capacidad:");

        cmbCapacidad.setBackground(new java.awt.Color(51, 51, 51));
        cmbCapacidad.setForeground(new java.awt.Color(255, 255, 255));
        cmbCapacidad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "100 Pasajeros", "200 Pasajeros", "300 Pasajeros", "400 Pasajeros" }));

        cmbConductoresDisponibles.setBackground(new java.awt.Color(51, 51, 51));
        cmbConductoresDisponibles.setForeground(new java.awt.Color(255, 255, 255));
        cmbConductoresDisponibles.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { ".", "." }));
        cmbConductoresDisponibles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbConductoresDisponiblesActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(153, 153, 153));
        jLabel9.setText("Conductor:");

        btnAnadirVehiculo.setBackground(new java.awt.Color(51, 153, 255));
        btnAnadirVehiculo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnAnadirVehiculo.setForeground(new java.awt.Color(255, 255, 255));
        btnAnadirVehiculo.setText("Añadir Vehiculo");

        jLabel10.setForeground(new java.awt.Color(255, 0, 0));
        jLabel10.setText("*Todos los campos son obligatorios");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 348, Short.MAX_VALUE))
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(IDvehiculotxt, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(aniofabricacionVehiculotxt, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(btnAnadirVehiculo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
                                .addComponent(cmbLineas, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbCapacidad, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbConductoresDisponibles, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(65, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IDvehiculotxt, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(aniofabricacionVehiculotxt, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbLineas, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbCapacidad, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbConductoresDisponibles, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58)
                .addComponent(btnAnadirVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void IDvehiculotxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDvehiculotxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IDvehiculotxtActionPerformed

    private void btnAnadirVehiculoActionPerformed(java.awt.event.ActionEvent evt) {
        if (!todosValidos()) {
            new ERRORview().setVisible(true);
            return;
        }

        new Confirmacion().setVisible(true);

        // Limpiar campos
        IDvehiculotxt.setText("");
        aniofabricacionVehiculotxt.setText("");
        IDvehiculotxt.putClientProperty("valido", false);
        aniofabricacionVehiculotxt.putClientProperty("valido", false);
        IDvehiculotxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(80,80,80),1,true));
        aniofabricacionVehiculotxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(80,80,80),1,true));
        cmbLineas.setSelectedIndex(0);
        cmbCapacidad.setSelectedIndex(0);
        cmbConductoresDisponibles.setSelectedIndex(0);
    }

    private void aniofabricacionVehiculotxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aniofabricacionVehiculotxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aniofabricacionVehiculotxtActionPerformed

    private void cmbConductoresDisponiblesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbConductoresDisponiblesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbConductoresDisponiblesActionPerformed


    // ── Inicialización y validaciones ─────────────────────────────────
    private void initColors() {
        IDvehiculotxt.setBackground(COLOR_CAMPO);
        IDvehiculotxt.setForeground(COLOR_TEXTO);
        aniofabricacionVehiculotxt.setBackground(COLOR_CAMPO);
        aniofabricacionVehiculotxt.setForeground(COLOR_TEXTO);
        cmbLineas.setBackground(COLOR_CAMPO);
        cmbLineas.setForeground(COLOR_TEXTO);
        cmbCapacidad.setBackground(COLOR_CAMPO);
        cmbCapacidad.setForeground(COLOR_TEXTO);
        cmbConductoresDisponibles.setBackground(COLOR_CAMPO);
        cmbConductoresDisponibles.setForeground(COLOR_TEXTO);
        btnAnadirVehiculo.setBackground(new java.awt.Color(51, 153, 255));
        btnAnadirVehiculo.setForeground(java.awt.Color.WHITE);
    }

    private void initPlaceholders() {
        configurarPlaceholder(IDvehiculotxt, "Ej. VTRAIN-928");
        configurarPlaceholder(aniofabricacionVehiculotxt, "Ej. 2023");
    }

    private void configurarPlaceholder(javax.swing.JTextField campo, String placeholder) {
        campo.setText(placeholder);
        campo.setForeground(new java.awt.Color(150, 150, 150));
        campo.addFocusListener(new java.awt.event.FocusAdapter() {
            @Override
            public void focusGained(java.awt.event.FocusEvent e) {
                if (campo.getText().equals(placeholder)) {
                    campo.setText("");
                    campo.setForeground(COLOR_TEXTO);
                }
            }
            @Override
            public void focusLost(java.awt.event.FocusEvent e) {
                if (campo.getText().trim().isEmpty()) {
                    campo.setText(placeholder);
                    campo.setForeground(new java.awt.Color(150, 150, 150));
                    marcarCampo(campo, false);
                }
            }
        });
    }

    private void initValidaciones() {
        IDvehiculotxt.getDocument().addDocumentListener(new SimpleDocListener(() -> {
            String v = IDvehiculotxt.getText().trim();
            marcarCampo(IDvehiculotxt, !v.isEmpty() && !v.equals("Ej. VTRAIN-928") && v.matches("[A-Za-z0-9\\- ]{5,}"));
        }));

        aniofabricacionVehiculotxt.getDocument().addDocumentListener(new SimpleDocListener(() -> {
            String v = aniofabricacionVehiculotxt.getText().trim();
            boolean ok = false;
            if (!v.isEmpty() && !v.equals("Ej. 2023") && v.matches("\\d{4}")) {
                try {
                    int y = Integer.parseInt(v);
                    int thisYear = java.time.LocalDate.now().getYear();
                    ok = y >= 1950 && y <= thisYear;
                } catch (Exception ex) { ok = false; }
            }
            marcarCampo(aniofabricacionVehiculotxt, ok);
        }));

        // Combos: marcar válidos si no están en su índice 0 (si se agrega placeholder en futuro)
        cmbLineas.addItemListener(e -> {
            if (e.getStateChange() != java.awt.event.ItemEvent.SELECTED) return;
            marcarCampo(cmbLineas, cmbLineas.getSelectedIndex() > -1);
        });
        cmbCapacidad.addItemListener(e -> {
            if (e.getStateChange() != java.awt.event.ItemEvent.SELECTED) return;
            marcarCampo(cmbCapacidad, cmbCapacidad.getSelectedIndex() > -1);
        });
        cmbConductoresDisponibles.addItemListener(e -> {
            if (e.getStateChange() != java.awt.event.ItemEvent.SELECTED) return;
            marcarCampo(cmbConductoresDisponibles, cmbConductoresDisponibles.getSelectedIndex() > -1);
        });
    }

    private void marcarCampo(javax.swing.JComponent campo, boolean valido) {
        java.awt.Color color = valido ? COLOR_OK : COLOR_ERROR;
        if (campo instanceof javax.swing.JTextField) {
            ((javax.swing.JTextField) campo).setBorder(javax.swing.BorderFactory.createCompoundBorder(
                javax.swing.BorderFactory.createLineBorder(color, 2, true),
                javax.swing.BorderFactory.createEmptyBorder(4, 8, 4, 8)
            ));
            campo.putClientProperty("valido", valido);
        } else if (campo instanceof javax.swing.JComboBox) {
            campo.setBorder(javax.swing.BorderFactory.createLineBorder(color, 2, true));
            campo.putClientProperty("valido", valido);
        }
    }

    private boolean todosValidos() {
        Object id = IDvehiculotxt.getClientProperty("valido");
        Object anio = aniofabricacionVehiculotxt.getClientProperty("valido");
        Object l = cmbLineas.getClientProperty("valido");
        Object c = cmbCapacidad.getClientProperty("valido");
        Object d = cmbConductoresDisponibles.getClientProperty("valido");
        return id instanceof Boolean && (Boolean) id
            && anio instanceof Boolean && (Boolean) anio
            && l instanceof Boolean && (Boolean) l
            && c instanceof Boolean && (Boolean) c
            && d instanceof Boolean && (Boolean) d;
    }

    private static class SimpleDocListener implements javax.swing.event.DocumentListener {
        private final Runnable accion;
        SimpleDocListener(Runnable accion) { this.accion = accion; }
        @Override public void insertUpdate(javax.swing.event.DocumentEvent e) { accion.run(); }
        @Override public void removeUpdate(javax.swing.event.DocumentEvent e) { accion.run(); }
        @Override public void changedUpdate(javax.swing.event.DocumentEvent e) { accion.run(); }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField IDvehiculotxt;
    private javax.swing.JTextField aniofabricacionVehiculotxt;
    private javax.swing.JButton btnAnadirVehiculo;
    private javax.swing.JComboBox<String> cmbCapacidad;
    private javax.swing.JComboBox<String> cmbConductoresDisponibles;
    private javax.swing.JComboBox<String> cmbLineas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
