/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vektra.View;

import java.awt.BorderLayout;
import java.util.List;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import vektra.Dao.ConductorDao;
import vektra.Model.Conductor;

/**
 *
 * @author santi
 */
public class ConductoresPanel extends javax.swing.JPanel {

    /**
     * Creates new form ConductoresPanel
     */
    private JScrollPane scrollTabla;
    private JTable tablaConductores;
    private MainFrameView mainFrame;

    public ConductoresPanel(MainFrameView frame) {
        this.mainFrame = frame;
        initComponents();
        crearTabla();
        cargarConductores();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        PaneldeConductores = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnAnadirConductor = new javax.swing.JButton();
        btnEliminarConductor = new javax.swing.JButton();
        btnAsignaraMetro = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout PaneldeConductoresLayout = new javax.swing.GroupLayout(PaneldeConductores);
        PaneldeConductores.setLayout(PaneldeConductoresLayout);
        PaneldeConductoresLayout.setHorizontalGroup(
            PaneldeConductoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 872, Short.MAX_VALUE)
        );
        PaneldeConductoresLayout.setVerticalGroup(
            PaneldeConductoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 380, Short.MAX_VALUE)
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Conductores");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 153, 153));
        jLabel2.setText("Gestión del personal de conducción");

        btnAnadirConductor.setBackground(new java.awt.Color(229, 229, 229));
        btnAnadirConductor.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAnadirConductor.setForeground(new java.awt.Color(0, 102, 204));
        btnAnadirConductor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vektra/View/Imagenes/ICONS CANVA/ADD.png"))); // NOI18N
        btnAnadirConductor.setText("Añadir Conductor");
        btnAnadirConductor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnadirConductorActionPerformed(evt);
            }
        });

        btnEliminarConductor.setBackground(new java.awt.Color(229, 227, 227));
        btnEliminarConductor.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEliminarConductor.setForeground(new java.awt.Color(102, 0, 0));
        btnEliminarConductor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vektra/View/Imagenes/ICONS CANVA/DELETE.png"))); // NOI18N
        btnEliminarConductor.setText("Borrar Conductor");
        btnEliminarConductor.setActionCommand("");
        btnEliminarConductor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarConductorActionPerformed(evt);
            }
        });

        btnAsignaraMetro.setBackground(new java.awt.Color(225, 223, 223));
        btnAsignaraMetro.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAsignaraMetro.setForeground(new java.awt.Color(0, 102, 204));
        btnAsignaraMetro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vektra/View/Imagenes/ICONS CANVA/ADDBUS.png"))); // NOI18N
        btnAsignaraMetro.setText("Asignar a Vehículo");
        btnAsignaraMetro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAsignaraMetroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnAnadirConductor, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addComponent(btnAsignaraMetro, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(btnEliminarConductor, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(PaneldeConductores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(PaneldeConductores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAnadirConductor, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminarConductor, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAsignaraMetro, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void crearTabla() {

        String columnas[] = {
            "ID",
            "Nombre",
            "Apellido",
            "Cedula",
            "Telefono",
            "Licencia",
            "Ruta"
        };

        DefaultTableModel modelo = new DefaultTableModel(columnas, 0);
        tablaConductores = new JTable(modelo);
        scrollTabla = new JScrollPane(tablaConductores);
        PaneldeConductores.setLayout(new BorderLayout());
        PaneldeConductores.removeAll();
        PaneldeConductores.add(scrollTabla, BorderLayout.CENTER);
        PaneldeConductores.revalidate();
        PaneldeConductores.repaint();
    }

    private void cargarConductores() {

        try {
            ConductorDao dao = new ConductorDao();
            List<Conductor> lista = dao.obtenerTodos();
            DefaultTableModel modelo = (DefaultTableModel) tablaConductores.getModel();

            modelo.setRowCount(0);

            for (Conductor c : lista) {
                modelo.addRow(new Object[]{
                    c.getId(),
                    c.getNombre(),
                    c.getApellido(),
                    c.getCedula(),
                    c.getTelefono(),
                    c.getLicencia(),
                    c.getRutaAsignada()
                });
            }

        } catch (Exception e) {

            System.out.println(
                    "Error cargando conductores: "
                    + e.getMessage()
            );
        }
    }

    private void btnAnadirConductorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnadirConductorActionPerformed

        mainFrame.mostrarPanel(new AnadirConductorPanel());
    }//GEN-LAST:event_btnAnadirConductorActionPerformed

    private void btnEliminarConductorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarConductorActionPerformed
        // TODO add your handling code here:
        mainFrame.mostrarPanel(new BorrarConductorPanel());
    }//GEN-LAST:event_btnEliminarConductorActionPerformed

    private void btnAsignaraMetroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAsignaraMetroActionPerformed
        // TODO add your handling code here:
        mainFrame.mostrarPanel(new AsignaraVehiculoPanel());
    }//GEN-LAST:event_btnAsignaraMetroActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PaneldeConductores;
    private javax.swing.JButton btnAnadirConductor;
    private javax.swing.JButton btnAsignaraMetro;
    private javax.swing.JButton btnEliminarConductor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
