/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vektra.View;

import java.util.List;
import vektra.Dao.TicketDao;
import vektra.Model.Ticket;

/**
 *
 * @author santi
 */
public class TicketsActivosPanel extends javax.swing.JPanel {

    /**
     * Creates new form TicketsActivosPanel
     */
    public TicketsActivosPanel() {
        initComponents();
        vektra.Util.FontUtil.applyCustomFont(this);
        cargarTicketsActivos();
    }

    private void cargarTicketsActivos() {
        try {
            TicketDao dao = new TicketDao();
            List<Ticket> tickets = dao.obtenerTicketsActivos();
            StringBuilder sb = new StringBuilder();
            if (tickets.isEmpty()) {
                sb.append("No hay tickets activos disponibles.\n");
            } else {
                for (Ticket t : tickets) {
                    sb.append("BOLETO\n");
                    sb.append("ID: ");
                    sb.append(t.getPasajero() != null ? t.getPasajero().getId() : "N/A");
                    sb.append("\n");
                    sb.append("NOMBRE DEL CLIENTE: ");
                    sb.append(t.getPasajero() != null ? t.getPasajero().getNombre() : "N/A");
                    sb.append("\n");
                    sb.append("ORIGEN: ");
                    sb.append(t.getEstacionOrigen() != null ? t.getEstacionOrigen().getNombre() : "N/A");
                    sb.append("\n");
                    sb.append("DESTINO: ");
                    sb.append(t.getEstacionDestino() != null ? t.getEstacionDestino().getNombre() : "N/A");
                    sb.append("\n");
                    sb.append("TIKET ID: ");
                    sb.append(t.getCodigo() != null ? t.getCodigo() : t.getId());
                    sb.append("\n");
                    sb.append("__________________\n\n");
                }
            }
            txtTicketsActivos.setText(sb.toString());
            txtTicketsActivos.setCaretPosition(0);
        } catch (Exception e) {
            txtTicketsActivos.setText("Error al cargar tickets: " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        PanelTicketsactivos = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtTicketsActivos = new javax.swing.JTextArea();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Tikects Activos");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 153, 153));
        jLabel2.setText("Tickets vigentes");

        txtTicketsActivos.setEditable(false);
        txtTicketsActivos.setBackground(new java.awt.Color(240, 240, 240));
        txtTicketsActivos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtTicketsActivos.setForeground(new java.awt.Color(51, 51, 51));
        txtTicketsActivos.setLineWrap(true);
        txtTicketsActivos.setWrapStyleWord(true);
        txtTicketsActivos.setBorder(javax.swing.BorderFactory.createEmptyBorder(12, 12, 12, 12));
        jScrollPane1.setViewportView(txtTicketsActivos);

        javax.swing.GroupLayout PanelTicketsactivosLayout = new javax.swing.GroupLayout(PanelTicketsactivos);
        PanelTicketsactivos.setLayout(PanelTicketsactivosLayout);
        PanelTicketsactivosLayout.setHorizontalGroup(
            PanelTicketsactivosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        PanelTicketsactivosLayout.setVerticalGroup(
            PanelTicketsactivosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 496, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PanelTicketsactivos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelTicketsactivos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelTicketsactivos;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtTicketsActivos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
